### ISSUE TITLE
No ARM64 version

### ISSUE THREAD

**Issue by conioh** [yunfandev/SQLite.uwp#1]
It would be helpful to have one. The ARM builds work on ARM64, but it might be better to use a native bitness.

**Comment by ionutdanila** [comment]
@conioh I couldn't find anywhere on the web the ARM64 build for SQLite UWP, so I created my own repository: [SQLite.UWP](https://github.com/ionutdanila/SQLite.UWP). There is also a NuGet Package that automatically selects the configuration (including ARM64): [SQLite.Universal](https://www.nuget.org/packages/SQLite.Universal/). 

I hope this helps you.
Best Regards,
